"""Purged + Embargoed K-Fold cross-validation (AFML Ch. 7).

The naive ``sklearn.model_selection.KFold`` / ``TimeSeriesSplit`` are **banned**
across this codebase because the labels of financial observations span time
intervals ``[t0_i, t1_i]`` — they are not IID. Two leakage paths must be sealed:

1. **Overlap purging.** For a sample ``i`` and a test fold spanning
   ``[T_start, T_end]``, sample ``i`` must be removed from train whenever its
   label horizon ``[t0_i, t1_i]`` overlaps the fold. Otherwise the model sees
   information that *was generated by* the test period.

2. **Embargo.** Even with purging, autocorrelation in returns can leak from the
   test period back into immediately-following train samples. Removing a small
   buffer after the test end (typically ``1 %`` of the series) is the AFML
   prescription.

The splitter is index-based — it operates on the *order* of events sorted by
``t0``. The caller supplies parallel ``t0`` / ``t1`` arrays and gets back
``(train_idx, test_idx)`` pairs that index back into the original (sorted)
position.

Phase 5 (Brain 2) reuses this splitter for its **Index-Intersection** DoD:
``max(train_t1) + embargo < min(test_t0)`` for every fold, millisecond
precision (Blueprint §7.3).
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass
from typing import Any

import numpy as np
import numpy.typing as npt

DEFAULT_N_SPLITS: int = 5
DEFAULT_EMBARGO_PCT: float = 0.01
# Minimum fraction of total samples each walk-forward training fold should
# accumulate before the first test fold starts. Below this, the early folds
# train on insufficient history; AFML recommends ≥ 30 %.
DEFAULT_WALK_FORWARD_TRAIN_FRACTION: float = 0.3


@dataclass(frozen=True, slots=True)
class PurgedKFold:
    """López de Prado purged + embargoed k-fold splitter.

    Parameters
    ----------
    n_splits
        Number of contiguous test folds. Each fold is a slice of the sample
        index sorted by ``t0``.
    embargo_pct
        Embargo as a fraction of the total sample count. ``0.01`` is the AFML
        default — generous enough to absorb realistic autocorrelation horizons
        without starving the training set.

    Examples
    --------
    >>> import numpy as np
    >>> t0 = np.arange(100, dtype=np.int64)
    >>> t1 = t0 + 5
    >>> cv = PurgedKFold(n_splits=4, embargo_pct=0.02)
    >>> for tr, te in cv.split(t0, t1):
    ...     assert len(np.intersect1d(tr, te)) == 0  # disjoint
    """

    n_splits: int = DEFAULT_N_SPLITS
    embargo_pct: float = DEFAULT_EMBARGO_PCT

    def __post_init__(self) -> None:
        if self.n_splits < 2:
            raise ValueError(f"n_splits must be ≥ 2, got {self.n_splits}")
        if not 0.0 <= self.embargo_pct < 0.5:
            raise ValueError(f"embargo_pct must be in [0, 0.5), got {self.embargo_pct}")

    def split(
        self,
        t0: npt.NDArray[np.int64] | npt.NDArray[np.floating],
        t1: npt.NDArray[np.int64] | npt.NDArray[np.floating],
    ) -> Iterator[tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]]]:
        """Yield ``(train_idx, test_idx)`` for each fold.

        Both ``t0`` and ``t1`` are 1-D arrays of the same length ``n``. ``t0[i]``
        is the start of sample ``i``'s label horizon, ``t1[i]`` its end. They
        may use any monotonic numeric encoding — integer indices, POSIX ms,
        ``np.datetime64`` casted to int64, etc.

        Yielded indices reference the *original* row order of ``t0`` / ``t1``
        (the splitter sorts internally; the indices it returns are pre-sort).
        Indices are guaranteed disjoint between train and test.
        """
        t0_arr = np.asarray(t0)
        t1_arr = np.asarray(t1)
        if t0_arr.shape != t1_arr.shape or t0_arr.ndim != 1:
            raise ValueError(
                f"t0 and t1 must be 1-D and same shape; got {t0_arr.shape} / {t1_arr.shape}"
            )
        if t0_arr.size < self.n_splits:
            raise ValueError(f"need ≥ n_splits samples; got {t0_arr.size} vs {self.n_splits}")
        if np.any(t1_arr < t0_arr):
            raise ValueError("every t1[i] must be ≥ t0[i] — label horizons cannot go backwards")

        n = t0_arr.size
        # Sort by t0; carry the original positions so we can return pre-sort indices.
        sort_order = np.argsort(t0_arr, kind="mergesort")
        t0_sorted = t0_arr[sort_order]
        t1_sorted = t1_arr[sort_order]

        embargo_size = int(np.floor(n * self.embargo_pct))

        fold_edges = np.linspace(0, n, self.n_splits + 1, dtype=np.int64)
        for fold in range(self.n_splits):
            test_start = int(fold_edges[fold])
            test_stop = int(fold_edges[fold + 1])  # exclusive
            if test_stop <= test_start:
                # Degenerate empty fold — shouldn't happen for valid n_splits.
                continue
            test_idx_sorted = np.arange(test_start, test_stop, dtype=np.int64)

            test_t0_min = t0_sorted[test_start]
            test_t1_max = t1_sorted[test_start:test_stop].max()

            # Train candidates are everything outside the test slice.
            train_mask = np.ones(n, dtype=bool)
            train_mask[test_start:test_stop] = False

            # PURGE: drop any train sample whose label horizon overlaps the
            # test window. Overlap test (closed intervals):
            #     t0_train ≤ test_t1_max  AND  t1_train ≥ test_t0_min
            overlap = (t0_sorted <= test_t1_max) & (t1_sorted >= test_t0_min)
            train_mask &= ~overlap

            # EMBARGO: drop the `embargo_size` samples immediately following
            # the test window. Their labels' t0 is later than the test fold
            # but autocorrelated returns may still bleed information.
            if embargo_size > 0:
                embargo_stop = min(n, test_stop + embargo_size)
                train_mask[test_stop:embargo_stop] = False

            train_idx_sorted = np.where(train_mask)[0]
            yield (
                sort_order[train_idx_sorted].astype(np.int64),
                sort_order[test_idx_sorted].astype(np.int64),
            )


class PurgedKFoldSklearn:
    """sklearn-CV-compatible adapter for :class:`PurgedKFold`.

    AFML 0-5 audit V1: ``sklearn.calibration.CalibratedClassifierCV`` (and any
    other sklearn CV consumer) accepts a ``cv`` object whose ``split(X, y,
    groups)`` returns ``(train_idx, test_idx)`` pairs. The underlying
    :class:`PurgedKFold` keys on label horizons ``(t0, t1)`` rather than on
    the rows of ``X``; this adapter holds the horizons internally and exposes
    sklearn's expected interface so the wrapper inside calibration / scoring
    code invokes **our** purged splits — never sklearn's default stratified
    KFold.

    Parameters
    ----------
    t0, t1
        Per-sample event horizons. Length must equal the number of rows
        ``sklearn`` will pass to :meth:`split` as ``X``.
    n_splits, embargo_pct
        Forwarded to :class:`PurgedKFold`.

    Examples
    --------
    >>> import numpy as np
    >>> from sklearn.calibration import CalibratedClassifierCV
    >>> from sklearn.ensemble import RandomForestClassifier
    >>> t0 = np.arange(200, dtype=np.int64)
    >>> t1 = t0 + 3
    >>> cv = PurgedKFoldSklearn(t0, t1, n_splits=4, embargo_pct=0.02)
    >>> # cv is now drop-in for any sklearn meta-estimator's ``cv`` argument.
    """

    def __init__(
        self,
        t0: npt.NDArray[np.int64] | npt.NDArray[np.floating],
        t1: npt.NDArray[np.int64] | npt.NDArray[np.floating],
        *,
        n_splits: int = DEFAULT_N_SPLITS,
        embargo_pct: float = DEFAULT_EMBARGO_PCT,
    ) -> None:
        self._t0 = np.asarray(t0)
        self._t1 = np.asarray(t1)
        if self._t0.shape != self._t1.shape or self._t0.ndim != 1:
            raise ValueError(
                f"t0 and t1 must be 1-D and same shape; got {self._t0.shape} / {self._t1.shape}"
            )
        self._inner = PurgedKFold(n_splits=n_splits, embargo_pct=embargo_pct)
        # Public-ish attributes — match what sklearn looks for on a CV object.
        self.n_splits = n_splits
        self.embargo_pct = embargo_pct

    def split(
        self,
        X: Any = None,
        y: Any = None,
        groups: Any = None,
    ) -> Iterator[tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]]]:
        # X / y / groups are part of sklearn's CV contract — unused here.
        del X, y, groups
        """Yield purged ``(train_idx, test_idx)`` pairs.

        Ignores ``X`` / ``y`` / ``groups`` — the splitter is parameterised by
        the per-sample ``(t0, t1)`` arrays passed at construction time.

        AFML 0-5 audit V1: this method is the literal hook sklearn's
        :class:`sklearn.calibration.CalibratedClassifierCV` calls during its
        ``.fit()`` cycle when this object is supplied as ``cv``. The unit test
        ``test_calibration_uses_purged_kfold_split`` confirms it is invoked.
        """
        yield from self._inner.split(self._t0, self._t1)

    def get_n_splits(
        self,
        X: Any = None,
        y: Any = None,
        groups: Any = None,
    ) -> int:
        """Number of folds — required by sklearn's CV interface."""
        del X, y, groups
        return self.n_splits


@dataclass(frozen=True, slots=True)
class PurgedWalkForwardCV:
    """Forward-only / chronological CV with purge + embargo (AFML Ch. 7).

    Unlike :class:`PurgedKFold` which yields two-sided folds (train comes from
    both sides of each test window), this splitter yields strictly
    forward-walking folds: every train sample is chronologically before every
    test sample in the same fold.

    This is exactly what Blueprint §7.3 Index-Intersection DoD asserts:
    ``max(train_t1) + embargo_time < min(test_t0)`` for every fold. The
    statement is one-sided and only consistent with walk-forward splits.

    Algorithm:

    1. Sort events by ``t0``.
    2. Reserve the first ``train_fraction × n`` events as the "burn-in" history
       — these never appear in a test fold.
    3. Divide the remainder into ``n_splits`` chronological test folds.
    4. For fold ``k``: train = events strictly before the test fold's start,
       minus any whose label horizon ``[t0, t1]`` extends into the test
       window, minus the embargo window's worth of samples immediately
       preceding the test fold.

    Parameters
    ----------
    n_splits
        Number of contiguous walk-forward test folds.
    embargo_pct
        Embargo width as a fraction of the total sample count. The embargo
        sits *between* the train tail and the test head.
    train_fraction
        Minimum burn-in fraction (default 0.3). The first fold's test set
        begins only after this many samples have already been seen.

    Examples
    --------
    >>> import numpy as np
    >>> t0 = np.arange(100, dtype=np.int64)
    >>> t1 = t0 + 3
    >>> cv = PurgedWalkForwardCV(n_splits=4, embargo_pct=0.02)
    >>> for tr, te in cv.split(t0, t1):
    ...     assert t1[tr].max() + 2 < t0[te].min()  # AFML index-intersection
    """

    n_splits: int = DEFAULT_N_SPLITS
    embargo_pct: float = DEFAULT_EMBARGO_PCT
    train_fraction: float = DEFAULT_WALK_FORWARD_TRAIN_FRACTION

    def __post_init__(self) -> None:
        if self.n_splits < 1:
            raise ValueError(f"n_splits must be ≥ 1, got {self.n_splits}")
        if not 0.0 <= self.embargo_pct < 0.5:
            raise ValueError(f"embargo_pct must be in [0, 0.5), got {self.embargo_pct}")
        if not 0.0 < self.train_fraction < 1.0:
            raise ValueError(f"train_fraction must be in (0, 1), got {self.train_fraction}")

    def split(
        self,
        t0: npt.NDArray[np.int64] | npt.NDArray[np.floating],
        t1: npt.NDArray[np.int64] | npt.NDArray[np.floating],
    ) -> Iterator[tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]]]:
        """Yield ``(train_idx, test_idx)`` for each chronological fold.

        Every yielded fold satisfies
        ``max(t1[train_idx]) + embargo_size < min(t0[test_idx])``
        (Blueprint §7.3 DoD), where ``embargo_size`` is the number of
        samples in the embargo window.
        """
        t0_arr = np.asarray(t0)
        t1_arr = np.asarray(t1)
        if t0_arr.shape != t1_arr.shape or t0_arr.ndim != 1:
            raise ValueError(
                f"t0 and t1 must be 1-D and same shape; got {t0_arr.shape} / {t1_arr.shape}"
            )
        n = t0_arr.size
        if n < self.n_splits + 1:
            raise ValueError(f"need ≥ n_splits + 1 samples; got {n} vs {self.n_splits}")
        if np.any(t1_arr < t0_arr):
            raise ValueError("every t1[i] must be ≥ t0[i] — label horizons cannot go backwards")

        sort_order = np.argsort(t0_arr, kind="mergesort")
        t0_sorted = t0_arr[sort_order]
        t1_sorted = t1_arr[sort_order]

        embargo_size = int(np.floor(n * self.embargo_pct))
        burn_in = int(np.floor(n * self.train_fraction))
        if burn_in >= n:
            raise ValueError(
                f"train_fraction {self.train_fraction} leaves no room for test folds; "
                f"burn_in={burn_in} ≥ n={n}"
            )
        if n - burn_in < self.n_splits:
            raise ValueError(
                f"not enough samples after burn-in: have {n - burn_in}, need ≥ {self.n_splits}"
            )

        # Test folds tile the post-burn-in region chronologically.
        fold_edges = np.linspace(burn_in, n, self.n_splits + 1, dtype=np.int64)
        for fold in range(self.n_splits):
            test_start = int(fold_edges[fold])
            test_stop = int(fold_edges[fold + 1])
            if test_stop <= test_start:
                continue
            test_idx_sorted = np.arange(test_start, test_stop, dtype=np.int64)
            test_t0_min = t0_sorted[test_start]

            # Train candidates are everything strictly before the test fold.
            train_mask = np.zeros(n, dtype=bool)
            train_mask[:test_start] = True

            # PURGE + EMBARGO in time units:
            # Blueprint §7.3 DoD asserts ``max(train_t1) + embargo_time < min(test_t0)``.
            # Equivalently: drop any train sample whose ``t1 + embargo_size``
            # reaches into (or past) the test fold's first ``t0``. Encoding the
            # embargo in TIME UNITS (matching ``t0`` / ``t1``) is what makes the
            # literal DoD assertion hold; a sample-count embargo would only
            # imply the weaker no-overlap purge.
            embargo_cut = (t1_sorted + embargo_size) >= test_t0_min
            train_mask &= ~embargo_cut

            train_idx_sorted = np.where(train_mask)[0]
            yield (
                sort_order[train_idx_sorted].astype(np.int64),
                sort_order[test_idx_sorted].astype(np.int64),
            )
