"""Purged + Embargoed K-Fold cross-validation (AFML Ch. 7).

The naive ``sklearn.model_selection.KFold`` / ``TimeSeriesSplit`` are **banned**
across this codebase because the labels of financial observations span time
intervals ``[t0_i, t1_i]`` — they are not IID. Two leakage paths must be sealed:

1. **Overlap purging.** For a sample ``i`` and a test fold spanning
   ``[T_start, T_end]``, sample ``i`` must be removed from train whenever its
   label horizon ``[t0_i, t1_i]`` overlaps the fold. Otherwise the model sees
   information that *was generated by* the test period.

2. **Embargo.** Even with purging, autocorrelation in returns can leak from the
   test period back into immediately-following train samples. Removing a small
   buffer after the test end (typically ``1 %`` of the series) is the AFML
   prescription.

The splitter is index-based — it operates on the *order* of events sorted by
``t0``. The caller supplies parallel ``t0`` / ``t1`` arrays and gets back
``(train_idx, test_idx)`` pairs that index back into the original (sorted)
position.

Phase 5 (Brain 2) reuses this splitter for its **Index-Intersection** DoD:
``max(train_t1) + embargo < min(test_t0)`` for every fold, millisecond
precision (Blueprint §7.3).
"""

from __future__ import annotations

from collections.abc import Iterator
from dataclasses import dataclass

import numpy as np
import numpy.typing as npt

DEFAULT_N_SPLITS: int = 5
DEFAULT_EMBARGO_PCT: float = 0.01


@dataclass(frozen=True, slots=True)
class PurgedKFold:
    """López de Prado purged + embargoed k-fold splitter.

    Parameters
    ----------
    n_splits
        Number of contiguous test folds. Each fold is a slice of the sample
        index sorted by ``t0``.
    embargo_pct
        Embargo as a fraction of the total sample count. ``0.01`` is the AFML
        default — generous enough to absorb realistic autocorrelation horizons
        without starving the training set.

    Examples
    --------
    >>> import numpy as np
    >>> t0 = np.arange(100, dtype=np.int64)
    >>> t1 = t0 + 5
    >>> cv = PurgedKFold(n_splits=4, embargo_pct=0.02)
    >>> for tr, te in cv.split(t0, t1):
    ...     assert len(np.intersect1d(tr, te)) == 0  # disjoint
    """

    n_splits: int = DEFAULT_N_SPLITS
    embargo_pct: float = DEFAULT_EMBARGO_PCT

    def __post_init__(self) -> None:
        if self.n_splits < 2:
            raise ValueError(f"n_splits must be ≥ 2, got {self.n_splits}")
        if not 0.0 <= self.embargo_pct < 0.5:
            raise ValueError(f"embargo_pct must be in [0, 0.5), got {self.embargo_pct}")

    def split(
        self,
        t0: npt.NDArray[np.int64] | npt.NDArray[np.floating],
        t1: npt.NDArray[np.int64] | npt.NDArray[np.floating],
    ) -> Iterator[tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]]]:
        """Yield ``(train_idx, test_idx)`` for each fold.

        Both ``t0`` and ``t1`` are 1-D arrays of the same length ``n``. ``t0[i]``
        is the start of sample ``i``'s label horizon, ``t1[i]`` its end. They
        may use any monotonic numeric encoding — integer indices, POSIX ms,
        ``np.datetime64`` casted to int64, etc.

        Yielded indices reference the *original* row order of ``t0`` / ``t1``
        (the splitter sorts internally; the indices it returns are pre-sort).
        Indices are guaranteed disjoint between train and test.
        """
        t0_arr = np.asarray(t0)
        t1_arr = np.asarray(t1)
        if t0_arr.shape != t1_arr.shape or t0_arr.ndim != 1:
            raise ValueError(
                f"t0 and t1 must be 1-D and same shape; got {t0_arr.shape} / {t1_arr.shape}"
            )
        if t0_arr.size < self.n_splits:
            raise ValueError(f"need ≥ n_splits samples; got {t0_arr.size} vs {self.n_splits}")
        if np.any(t1_arr < t0_arr):
            raise ValueError("every t1[i] must be ≥ t0[i] — label horizons cannot go backwards")

        n = t0_arr.size
        # Sort by t0; carry the original positions so we can return pre-sort indices.
        sort_order = np.argsort(t0_arr, kind="mergesort")
        t0_sorted = t0_arr[sort_order]
        t1_sorted = t1_arr[sort_order]

        embargo_size = int(np.floor(n * self.embargo_pct))

        fold_edges = np.linspace(0, n, self.n_splits + 1, dtype=np.int64)
        for fold in range(self.n_splits):
            test_start = int(fold_edges[fold])
            test_stop = int(fold_edges[fold + 1])  # exclusive
            if test_stop <= test_start:
                # Degenerate empty fold — shouldn't happen for valid n_splits.
                continue
            test_idx_sorted = np.arange(test_start, test_stop, dtype=np.int64)

            test_t0_min = t0_sorted[test_start]
            test_t1_max = t1_sorted[test_start:test_stop].max()

            # Train candidates are everything outside the test slice.
            train_mask = np.ones(n, dtype=bool)
            train_mask[test_start:test_stop] = False

            # PURGE: drop any train sample whose label horizon overlaps the
            # test window. Overlap test (closed intervals):
            #     t0_train ≤ test_t1_max  AND  t1_train ≥ test_t0_min
            overlap = (t0_sorted <= test_t1_max) & (t1_sorted >= test_t0_min)
            train_mask &= ~overlap

            # EMBARGO: drop the `embargo_size` samples immediately following
            # the test window. Their labels' t0 is later than the test fold
            # but autocorrelated returns may still bleed information.
            if embargo_size > 0:
                embargo_stop = min(n, test_stop + embargo_size)
                train_mask[test_stop:embargo_stop] = False

            train_idx_sorted = np.where(train_mask)[0]
            yield (
                sort_order[train_idx_sorted].astype(np.int64),
                sort_order[test_idx_sorted].astype(np.int64),
            )
